### ISSUE TITLE
[Forge] Mods that affect hotbar render a bit weird

### ISSUE THREAD

**Issue by BugmanBugman** [RaphiMC/ImmediatelyFast#116]
Before IF: 
![2023-09-16_18 36 40](https://github.com/RaphiMC/ImmediatelyFast/assets/40730042/0d26dbce-8149-438c-b9a0-a34999398a9c)
After:

![2023-09-16_18 33 00](https://github.com/RaphiMC/ImmediatelyFast/assets/40730042/7360ffa4-1159-4e3d-898a-058fcf02d2dc)

I am using mods such as https://www.curseforge.com/minecraft/mc-mods/item-borders and https://legacy.curseforge.com/minecraft/mc-mods/item-highlighter that affect items in the hot bar. As you can see the in the before picture, the item with the green border is very much highlighted, but in the after pic, the gems with blue and green borders are far more subdued and hidden.

**Comment by RaphiMC** [comment]
Will be fixed in the next release. Here are snapshot builds of IF with the fix:
https://upload.raphimc.net/file/MQxO5LHAd3XBXM4J/wHj9stmKw8DScYDZ/ImmediatelyFast-1.2.6-SNAPSHOT%2B1.19.2.jar
https://upload.raphimc.net/file/pUww0ZJX06KBsxtb/rQHD6uvyl7jYR4Q1/ImmediatelyFast-1.2.6-SNAPSHOT%2B1.19.4.jar
https://upload.raphimc.net/file/UFGTodFxwSDCIRFm/9OhGEUkAV1oZRQ05/ImmediatelyFast-1.2.6-SNAPSHOT%2B1.20.2.jar
