### ISSUE TITLE
”Item Highlighter“compatibility

### ISSUE THREAD

**Issue by wsxiya** [RaphiMC/ImmediatelyFast#118]
![5PQ5 LGT{M%9{XN`T{UE 0Z](https://github.com/RaphiMC/ImmediatelyFast/assets/114494454/daec31b3-8761-41b1-a957-ad98e4c4e2ba)
![PCY`76`@14$EOA88)LUIG20](https://github.com/RaphiMC/ImmediatelyFast/assets/114494454/4fd47f04-8784-4cb5-b1c0-3dca3745bfe7)

**Comment by wsxiya** [comment]
https://www.curseforge.com/minecraft/mc-mods/item-highlighter-fabric

**Comment by RaphiMC** [comment]
Can you provide an image of how its supposed to look

**Comment by wsxiya** [comment]
![5PQ5 LGT{M%9{XN`T{UE 0Z](https://github.com/RaphiMC/ImmediatelyFast/assets/114494454/dd7571b5-1cb0-4da1-8c6b-7637e685d5ba)

**Comment by wsxiya** [comment]
It should be like this

**Comment by wsxiya** [comment]
But it can be solved by modifying this item in the config configuration ""hud_batching": true," to false, but the optimization effect may be reduced.

**Comment by RaphiMC** [comment]
Thanks for reporting, I will look into this issue when there is time

**Comment by wsxiya** [comment]
Thanks

**Comment by RaphiMC** [comment]
Will be fixed in the next release. Here are snapshot builds of IF with the fix:
https://upload.raphimc.net/file/MQxO5LHAd3XBXM4J/wHj9stmKw8DScYDZ/ImmediatelyFast-1.2.6-SNAPSHOT%2B1.19.2.jar
https://upload.raphimc.net/file/pUww0ZJX06KBsxtb/rQHD6uvyl7jYR4Q1/ImmediatelyFast-1.2.6-SNAPSHOT%2B1.19.4.jar
https://upload.raphimc.net/file/UFGTodFxwSDCIRFm/9OhGEUkAV1oZRQ05/ImmediatelyFast-1.2.6-SNAPSHOT%2B1.20.2.jar
