### ISSUE TITLE
”Item Borders [Forge]“compatibility

### ISSUE THREAD

**Issue by sh3rfy** [RaphiMC/ImmediatelyFast#119]
**MC:**
1.19.2
**Forge:** 
43.2.23

ItemBorders-1.19.1-1.2.0.jar
ImmediatelyFast-1.2.5+1.19.2.jar

[Curseforge](https://www.curseforge.com/minecraft/mc-mods/item-borders)
[Modrinth](https://modrinth.com/mod/item-borders)

Should look like this:
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/73312403/3f64fed0-c07a-4db1-9d5c-1f77ae0949ee)

Looks like this:
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/73312403/56487664-4b98-401c-8a3d-fba19f62c0af)

Bug appears only in toolbar.
With ImmediatelyFast-1.2.1+1.19.2.jar, I don't have this issue.

**Comment by RaphiMC** [comment]
Will be fixed in the next release. Here are snapshot builds of IF with the fix:
https://upload.raphimc.net/file/MQxO5LHAd3XBXM4J/wHj9stmKw8DScYDZ/ImmediatelyFast-1.2.6-SNAPSHOT%2B1.19.2.jar
https://upload.raphimc.net/file/pUww0ZJX06KBsxtb/rQHD6uvyl7jYR4Q1/ImmediatelyFast-1.2.6-SNAPSHOT%2B1.19.4.jar
https://upload.raphimc.net/file/UFGTodFxwSDCIRFm/9OhGEUkAV1oZRQ05/ImmediatelyFast-1.2.6-SNAPSHOT%2B1.20.2.jar
