### ISSUE TITLE
Another incompatibility with YTTR (F3 screen)

### ISSUE THREAD

**Issue by Abalieno** [RaphiMC/ImmediatelyFast#14]
F3 screen doesn't show any text when both YTTR and ImmediatelyFast are present. It works fine with either of them, it doesn't when the two are together. 

ImmediatelyFast-1.19-1.1.2
yttr-7.638+1.19.2

**Comment by exaskye** [comment]
You don't even give me 3 seconds to test this for myself before reporting it to the other party. It's unlikely ImmediatelyFast is doing anything wrong.

**Comment by exaskye** [comment]
Reproduced with Lucium (the mod I told you Yttr includes that would cause this, and not Yttr itself), looking into it.

**Comment by exaskye** [comment]
Disabling this mixin fixes it: https://github.com/RaphiMC/ImmediatelyFast/blob/1.19.3/src/main/java/net/raphimc/immediatelyfast/injection/mixins/batching/MixinDebugHud.java

So for some reason batching the debug hud is breaking Lucium's debug hud rework.

I'll take ownership and responsibility of this; please close.

----

EDIT: A mixin export makes it quite obvious why this happens:

![image](https://user-images.githubusercontent.com/6185037/210101121-b509f534-8113-49c9-bfd4-9bf617c7d278.png)

The batch is never ended due to the way the mixins order. I'll add a call into `endBatching` in my code.

**Comment by RaphiMC** [comment]
This is actually an issue in ImmediatelyFast. I intended for the mixins to order in such a way that my mixins are applied last and thus inject before the return instruction your mixin added. But mixins doesn't seem to work that way. I will fix it differently on my side as well

**Comment by exaskye** [comment]
It's not possible to inject before another mod's cancel in that way. You would hope and wish that `RETURN` matches other injects, but it just doesn't.

The best you would be able to do is inject before Lucium's entire inject, but that won't help either.

**Comment by RaphiMC** [comment]
I am now "redirecting" the call inside the render method. I use mixins extras for that so it will be compatible with other mods redirecting it as well
