### ISSUE TITLE
Library causes Antivirus to trigger

### ISSUE THREAD

**Issue by Arbee4ever** [RaphiMC/ImmediatelyFast#142]
As reported in https://github.com/xR4YM0ND/Aged/issues/17 the Reflect Library from lenny0451 causes antivirus programs to flag it as a Trojan.
Even though it's most definitely a false positive i'd suggest using mixins instead.

Architectury Mixin Docs: https://docs.architectury.dev/loom/mixins

**Comment by RaphiMC** [comment]
Thanks for reporting. This is already known and I am trying to find a fix for the next version of IF. Reflect is currently needed for high performance accessors to other mods and I cant simply replace it with mixins. Mixin doesn't allow me to access fields or invoke methods of other mods without directly injecting into them. Injecting into those mods is not ideal since I would have to (soft)depend on the mod to by able to access its code regularly. Reflect allows me to make high performance accessors without needing to depend on the mod or modify its code.

**Comment by RaphiMC** [comment]
Linked issue: https://github.com/Lenni0451/Reflect/issues/3

**Comment by RaphiMC** [comment]
The library fixed the issue apparently and I will include the updated version in the next release of ImmediatelyFast
