### ISSUE TITLE
ImmediatelyFast has a Trojan

### ISSUE THREAD

**Issue by GangsMitglied** [RaphiMC/ImmediatelyFast#157]
My antivirus detected a trojan with this mod

**Comment by RaphiMC** [comment]
Already fixed (https://github.com/RaphiMC/ImmediatelyFast/issues/142). Update ImmediatelyFast

**Comment by GangsMitglied** [comment]
My antivirus detected it today

**Comment by RaphiMC** [comment]
You can provide more details like which antivirus or what ImmediatelyFast is being detected for, but I can't do much about it since Antivirus software is usually pretty bad when it comes to jar files. The only thing I can imagine is reporting it to the antivirus vendor and hope they remove the false positive, but some might ignore it

**Comment by GangsMitglied** [comment]
I use Bitdefender and it is detected as a Trojan

**Comment by GangsMitglied** [comment]
But everything is fine, I read the chat history https://github.com/RaphiMC/ImmediatelyFast/issues/142
