### ISSUE TITLE
[HUD optimization] Issue with Armour Chroma mod

### ISSUE THREAD

**Issue by RaptaG** [RaphiMC/ImmediatelyFast#19]
Some parts turned black:

![Bug](https://user-images.githubusercontent.com/77157639/210367721-67a7d8f1-60d2-4a9a-87ca-1e2b9bfcb205.png)

Mod: https://modrinth.com/mod/armor-chroma-for-fabric

**Comment by RaphiMC** [comment]
Will be fixed in ImmediatelyFast 1.1.6. Here are some test builds because 1.1.6 will be published after I fixed the Iris issue (Which may take a while because I need to communicate with Iris devs)
[ImmediatelyFast-1.1.6.zip](https://github.com/RaphiMC/ImmediatelyFast/files/10338826/ImmediatelyFast-1.1.6.zip)
