### ISSUE TITLE
How does IF optimize block entities and is it compatible with EBE?

### ISSUE THREAD

**Issue by RaptaG** [RaphiMC/ImmediatelyFast#2]
Also, is it compatible with Exordium (FasterGUI)?

**Comment by RaphiMC** [comment]
IF does optimize block entities because they are being rendered in immediate mode by default. EBE replaces the whole vanilla block entity rendering code and makes it non immedate mode. This means IF won't do anything additionally. Also it is compatible with Exordium, but will not optimize any GUI/Text which was already optimized by Exordium. Exordium also replaces parts of the immediate mode rendering with non immediate mode rendering. Having IF installed alongside all of those mods should not cause any problems and might improve performance on some other places which use immediate mode rendering (Also any other mosd which might).
