### ISSUE TITLE
Tab list is blacked out / Essential mod compatibility (1.20.4)

### ISSUE THREAD

**Issue by Hlebuw3k** [RaphiMC/ImmediatelyFast#213]
The current workaround is to "Just disable the Essential indicator in tab-list on essential settings" as [yichifauzi](https://github.com/yichifauzi) has pointed out.
With mod:
![Снимок экрана 2024-05-12 070944](https://github.com/RaphiMC/ImmediatelyFast/assets/78320892/f3cc80af-981d-4ebb-9b4f-f332240e2fd4)
Without mod:
![Снимок экрана 2024-05-12 070119](https://github.com/RaphiMC/ImmediatelyFast/assets/78320892/8e162160-0596-4338-99bb-d8a93006a6e0)
Modlist (ImmediatelyFast removed due to tab list blackout):
![modlist](https://github.com/RaphiMC/ImmediatelyFast/assets/78320892/7c626f6f-f9dc-454b-890a-b7d68b562ca1)

**Comment by RaphiMC** [comment]
Please try to reproduce this problem only with ImmediatelyFast installed. If it doesn't happen with only ImmediatelyFast installed try finding out which mod causes it in combination with ImmediatelyFast. When you reproduced the bug with a minimal mod list upload the game log

**Comment by dirtTW** [comment]
![2024-05-21_02 07 24](https://github.com/RaphiMC/ImmediatelyFast/assets/31981880/5b8ccfe6-c636-4e62-a598-e98ad59f7211)


https://mclo.gs/oAK2vYc

the bug happen when using essential mod when in server.... need to report on essential side....

EDIT: I been report to them and i found a temporary solution for essential 
Just disable the Essential indicator in tab-list on essential settings

**Comment by DJtheRedstoner** [comment]
Hi, Essential developer here.

I've identified that this is caused by your HUD Batching feature. We have a feature which renders a diamond indicator in the tab menu next to player names to show other players that are using Essential.
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/52044242/7b5c7f3e-8eac-410f-93b9-0085fc5de648)

Our code is pretty simple, however it notably doesn't use DrawContext's methods due to the wide range of versions we support (and since there's none that are appropriate for this diamond/rotated square anyways). This seems to be what causes the issue to occur, since [PlayerListHud is batched](https://github.com/RaphiMC/ImmediatelyFast/blob/702a3aa9459e7079318dab322781b5f97ce9d899/common/src/main/java/net/raphimc/immediatelyfast/injection/mixins/hud_batching/MixinPlayerListHud.java).

Would the appropriate fix here be to use the api to implement something like [the armor chroma compat mixin](https://github.com/RaphiMC/ImmediatelyFast/blob/702a3aa9459e7079318dab322781b5f97ce9d899/common/src/main/java/net/raphimc/immediatelyfast/injection/mixins/hud_batching/compat/armorchroma/MixinArmorChroma_GuiArmor.java)? I'd rather this be on our side (as opposed to a compat mixin in ImmediatelyFast), since this code will likely change in the future. A quick test seems to show that this works.

**Comment by PolyframeX** [comment]
This issue occures on 1.20.1 as well.

**Comment by RaphiMC** [comment]
@DJtheRedstoner A fix similar to the armor chroma fix should work and would be the ideal solution if the underlying rendering code doesn't use DrawContext and thus can't be easily batched with IF.

**Comment by LordEnder-Kitty** [comment]
@yichifauzi Oh my gosh, thank you. i tried to figure out what was causing the issue but couldn't find in in my testing because i didn't think Essential would be the problem. 
I've also noticed that Essential emotes aren't rendering. im not sure if that's also this mod causing the issue, but it started around when i updated this, so.

**Comment by Reinified** [comment]
I have an issue just like this with immediatleyfast & essentials mod in my modpack, however it seems to block out certain names at random in the tablist

examples:
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/54984650/47620da7-de4a-44d7-b448-acb0ad9bf537)
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/54984650/20aa326d-9835-4196-a319-fd02505d3aaf)

**Comment by Hlebuw3k** [comment]
Essential Mod fixed this in the version 1.3.2.5, change log: https://modrinth.com/mod/essential/version/vXxBUert
(tested it myself in-game to make sure, the issue no longer occurs)
