### ISSUE TITLE
Question about Lunar Client Support

### ISSUE THREAD

**Issue by kispintyi** [RaphiMC/ImmediatelyFast#223]
Given that either you support Feather Client or Feather Client supports this mod, is it possible that Lunar Client might also get supported sometime?

**Comment by RaphiMC** [comment]
I am not supporting any custom clients officialy. It just happens that the Feather Client devs (and soon maybe the Essential devs) are the only ones that were willing to fix the issues on their side. If you want to get Lunar Client support, you have to ask them to fix the issues within Lunar Client itself. I can't properly diagnose issues with Lunar Client myself because its a closed source client.

**Comment by kispintyi** [comment]
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/116653691/dc776fc9-71c7-454c-beaf-222b30c5e5df)

**Comment by chedcraft** [comment]
still dosnt work, it gives me a black screen and then it crashes(its compatible with my mods, cus when using modrinth everything works fine with the same mods i have)

**Comment by kispintyi** [comment]
Lunar still doesn't support it.
