### ISSUE TITLE
The level is not displayed correctly

### ISSUE THREAD

**Issue by MCSmallCai** [RaphiMC/ImmediatelyFast#49]
After my tests, it seems that when ImmediatelyFast and an optimized module called Caxton installed together, the level display will be separated from the taskbar and placed at the bottom of the taskbar (I installed the Raised module, this module can raise and lower the taskbar, and the level display will not move together when I raise and lower the taskbar) 
![2023-03-18_11 14 38](https://user-images.githubusercontent.com/121654450/226081962-a5c60bc1-d81b-46fd-9d71-08ed2e3b6804.png)
The first image shows the installation of ImmediatelyFast-1.1.10+1.19 and caxton 0.4.0 beta. 4+1.19.2 together
![2023-03-18_11 20 34](https://user-images.githubusercontent.com/121654450/226082259-f04362e3-3d4f-4387-a10b-0f0464a64768.png)
The second image only installs ImmediatelyFast-1.1.10+1.19
![2023-03-18_11 24 25](https://user-images.githubusercontent.com/121654450/226082123-269ec95c-39d2-4c10-b8fa-2cb78ae707de.png)
The third image only installs caxton-0.4.0-beta.4+1.19.2

**Comment by MCSmallCai** [comment]
I tested it again. ImmediatelyFast does not separate the level display from the taskbar. The Caxton module will

**Comment by RaphiMC** [comment]
Is this an issue related to ImmediatelyFast?

**Comment by bluebear94** [comment]
Hi, I’m the developer of Caxton and I got a [report of this bug](https://gitlab.com/Kyarei/caxton/-/issues/40) as well.

I think I know what’s going on. ImmediatelyFast [sets calls to `TextRenderer` methods to draw to `BatchingBuffers.TEXT_CONSUMER` by default](https://github.com/RaphiMC/ImmediatelyFast/blob/1.19.4/src/main/java/net/raphimc/immediatelyfast/injection/mixins/hud_batching/consumer/MixinTextRenderer.java), but Caxton’s XP text rendering tweak doesn’t call any of these methods at all (it calls `CaxtonText.drawWithOutline`, bypassing the whole `TextRenderer` thing). This results in the XP text being drawn in the same draw call as elements such as the XP bar instead of with the other text.

Caxton’s XP text rendering tweak, in turn, is a workaround for another compatibility issue between Caxton and ImmediatelyFast that causes [text overlapping](https://gitlab.com/Kyarei/caxton/-/issues/31) that does not occur without Caxton.

**Comment by RaphiMC** [comment]
The workaround shouldn't be needed anymore

**Comment by bluebear94** [comment]
Nope, this is what I get when I disable the `tweakExpText` option in Caxton (0.4.0-beta.4, Minecraft 1.19.2, IF 1.1.10):

![2023-03-18_07 24 41](https://user-images.githubusercontent.com/2975203/226102309-0c41f306-3371-4928-bafc-c1b0db0f1055.png)

**Comment by RaphiMC** [comment]
I will look into the issue myself later with proper rendering debugging tools and let you know what I found

**Comment by bluebear94** [comment]
Thank you for your time!

**Comment by RaphiMC** [comment]
I looked through your code a bit and saw that you define custom RenderLayer's for caxton (CaxtonTextRenderLayers). If you copied the definition from Minecraft (Which it looks like) you have to manually apply https://github.com/RaphiMC/ImmediatelyFast/blob/1.19.4/src/main/java/net/raphimc/immediatelyfast/injection/mixins/core/MixinRenderLayer.java to your RenderLayer's. (The mixin just disables translucency for all text related RenderLayer's)
 Disabling translucency for text should cause not problems and can be done even if ImmediatelyFast isn't loaded.

After you have changed that you shouldn't need that workaround anymore and everything should render properly. If thats the case let me know so I can close the issue

**Comment by bluebear94** [comment]
Isn’t the translucency setting necessary for sorting primitives from back-to-front order so they display correctly if there’s text that contains partially transparent pixels?

**Comment by RaphiMC** [comment]
Yes, but minecraft never comes in a situation where the primitives for text would ever need to be sorted because text is drawn immediately in minecraft and not buffered (Which means text can't overlap anything in the same draw call). The problem with the sorting is that it sorts the shadow as well if there are multiple overlapping characters in the same BufferBuilder (Which in vanilla never happens because all text render calls draw immediately without buffering). This patch has been in ImmediatelyFast for months and there are not reports of text rendering errors yet, so I assume this is safe to do

**Comment by RaphiMC** [comment]
@bluebear94 Is this now resolved? Looks like you already pushed a fix in caxton

**Comment by bluebear94** [comment]
Yes, it should work if you disable the `tweakExpText` option. The experience bar text does look better for outline fonts with that option enabled, but that problem can be solved later.

**Comment by RaphiMC** [comment]
If I understood the code correctly that option bypasses the normal rendering of text (it isn't written into the vertex consumer, but drawn immediately instead) and I can't really do much about that on my side. You could end the current HUD batch of ImmediatelyFast (Force draw all the buffer contents and then draw the caxton text and then start the batching again): ``BatchingBuffers.beginHudBatching();`` and ``BatchingBuffers.endHudBatching();``. Also good to check if ImmediatelyFast is currently batching: ``BatchingBuffers.isTextBatching();`` before doing any of the other operations.

I will close the issue, but you can write another comment if you have further questions.
